md build

cd build

cmake .. ^
	-DMUGGLE_BUILD_SHARED_LIB=ON ^
	-DMUGGLE_BUILD_EXAMPLE=ON ^
	-DMUGGLE_BUILD_TESTING=OFF ^
	-DMUGGLE_BUILD_BENCHMARK=OFF ^
	-DMUGGLE_BUILD_TRACE=OFF ^
	-DMUGGLE_EXTRA_PREFIX_PATH=f:/c_pkg ^
	-G "Visual Studio 14 2015 Win64"
