#!/bin/bash

mkdir build

cd build

cmake .. \
	-DMUGGLE_BUILD_TRACE=OFF \
	-DMUGGLE_BUILD_SHARED_LIB=ON \
	-DMUGGLE_BUILD_EXAMPLE=ON \
	-DMUGGLE_BUILD_TESTING=OFF \
	-DMUGGLE_BUILD_BENCHMARK=OFF \
	-DBUILD_TESTING=OFF \
	-DMUGGLE_CRYPT_OPTIMIZATION=ON \
	-DMUGGLE_CRYPT_COMPARE_OPENSSL=OFF
