name: Android NDK CMake

on: [push, pull_request]

jobs:
  build:
    name: Android NDK CMake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-android@v2
      - names: build
        run: |
          mkdir build;
          cd build;
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a;
