name: Android

on: [push, pull_request]

jobs:
  build:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - name: build
        run: |
          mkdir build;
          cd build;
          cmake ..  \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI;
          cmake --build . --config Release;
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          ABI: arm64-v8a
      #- name: tests
      #  uses: reactivecircus/android-emulator-runner@v2
      #  run: >
      #    cd build;
      #    cmake --build . --target test;
